ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'MONTHLY_CHARGE';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'CASH_PAID';

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_indefinitely_paused BOOLEAN NOT NULL DEFAULT FALSE;
