-- Migration: Add missing values to transaction_type and user_role ENUM types

ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'MONTHLY_CHARGE';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'PENALTY';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'DISCOUNT';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'RECHARGE';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'CASH_PAID';

ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'OWNER';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'FINANCE_ADMIN';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'MEAL_MANAGER';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'HOSTEL_MANAGER';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'AUDITOR';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SUPPORT_ADMIN';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'READONLY_ADMIN';
