export const BN = {
  appTitle: "মিল ম্যানেজার PRO",
  appSubtitle: "স্মার্ট হোস্টেল মিল ও ফাইন্যান্স প্ল্যাটফর্ম (V4 Enterprise)",
  tagline: "সহজ, নির্ভুল ও আধুনিক মিল এবং ওয়ালেট ব্যবস্থাপনা",
  tkSymbol: "৳",

  // Navigation & Tabs
  dashboard: "ড্যাশবোর্ড",
  meals: "মিল ম্যানেজমেন্ট",
  mealDeclaration: "মিল ডিক্লেয়ারেশন",
  wallet: "মাই ওয়ালেট",
  reports: "রিপোর্ট ও হিস্ট্রি",
  adminPanel: "অ্যাডমিন হাব",
  users: "রেসিডেন্ট তালিকা",
  settings: "সিস্টেম সেটিংস",
  logout: "লগআউট",
  login: "লগইন",
  register: "রেজিস্ট্রেশন",

  // Account Modes
  adminMode: "অ্যাডমিন মোড",
  userMode: "ইউজার মোড",
  switchMode: "মোড পরিবর্তন",
  switchModeTooltip: "অ্যাডমিন এবং ইউজার মোডের মধ্যে সুইচ করুন",

  // Role Labels
  superAdmin: "সুপার অ্যাডমিন",
  financeAdmin: "ফাইন্যান্সিয়াল অ্যাডমিন",
  mealManager: "মিল ম্যানেজার",
  hostelManager: "হোস্টেল ম্যানেজার",
  branchManager: "ব্রাঞ্চ ম্যানেজার",
  auditor: "অডিট অফিসার",
  supportAdmin: "সাপোর্ট টিম",
  readonlyAdmin: "পর্যবেক্ষক",
  userRole: "সাধারণ রেসিডেন্ট",

  // User Types
  permanentUser: "স্থায়ী রেসিডেন্ট",
  guestUser: "গেস্ট মেম্বার",
  selectUserType: "মেম্বারশিপ ধরণ বেছে নিন",

  // Meal Labels
  breakfast: "সকালের নাস্তা",
  lunch: "দুপুরের খাবার",
  dinner: "রাতের খাবার",
  mealOn: "চালু",
  mealOff: "বন্ধ",
  autoCopied: "স্বয়ংক্রিয় যুক্ত (Auto Copied)",
  userDeclared: "ম্যানুয়ালি এন্ট্রি (User Declared)",
  todayMealStatus: "আজকের মিল স্ট্যাটাস",
  deadlineNotice: "১০:০০ AM ডেডলাইন নোটিশ",
  autoCopyNotice: "ডেডলাইন পার হলে গতকালের মিল কপি হবে",
  masterMealSwitch: "মাস্টার মিল অন/অফ সুইচ",

  // Financial Dashboard & Wallet
  currentBalance: "বর্তমান ওয়ালেট ব্যালেন্স",
  financialDashboard: "ফাইন্যান্সিয়াল ড্যাশবোর্ড",
  todayCollection: "আজকের সংগৃহীত অর্থ",
  monthlyCollection: "চলতি মাসের মোট কালেকশন",
  yearlyCollection: "চলতি বছরের কালেকশন",
  todayExpenses: "আজকের আনুমানিক খরচ",
  netProfit: "নিট প্রফিট / ব্যালেন্স",
  outstandingBalance: "বকেয়া পরিমাণ",
  totalWalletBalance: "ইউজারদের মোট ওয়ালেট জমা",
  totalRefunds: "মোট ফেরত দেওয়া অর্থ",
  totalRecharge: "মোট রিচার্জ",
  totalDeduction: "মোট কর্তন",
  totalRevenue: "মোট রাজস্ব কালেকশন",
  permanentRevenue: "স্থায়ী রেসিডেন্ট রাজস্ব",
  guestRevenue: "গেস্ট মেম্বার রাজস্ব",
  topSpenders: "সর্বোচ্চ খরচকারী মেম্বার",
  lowBalanceAlertTitle: "লো ব্যালেন্স অ্যালার্ট",
  recharge: "রিচার্জ",
  deduction: "মিল কর্তন",
  monthlyCharge: "মাসিক ফি",
  permRates: "স্থায়ী রেসিডেন্ট রেটসমূহ",
  guestRates: "গেস্ট মেম্বার রেটসমূহ",
  confirmTopUp: "রিচার্জ নিশ্চিত করুন",

  // AI Business Intelligence
  aiInsightTitle: "AI বিজনেস ইন্টেলিজেন্স ও পূর্বাভাস",
  aiRevenueForecast: "পূর্বাভাসকৃত পরবর্তী মাসের রাজস্ব",
  aiMealForecast: "প্রত্যাশিত মিল চাহিদা",
  aiRiskLevel: "আর্থিক ঝুঁকিসূচক",
  aiRecommendations: "স্মার্ট সুপারিশমালা",

  // Search & Filter & Actions
  advancedSearchPlaceholder: "নাম, ফোন, স্টুডেন্ট আইডি, বিভাগ বা রুম দিয়ে খুঁজুন...",
  searchUser: "মেম্বার খুঁজুন",
  filterByUserType: "মেম্বারশিপ টাইপ",
  filterByRole: "অ্যাডমিন রোল",
  filterByBranch: "ব্রাঞ্চ নির্বাচন",
  filterByStatus: "অনুমোদন স্ট্যাটাস",
  allBranches: "সকল হোস্টেল ব্রাঞ্চ",
  saveChanges: "পরিবর্তন সংরক্ষণ করুন",
  viewDetails: "বিস্তারিত দেখুন",
  approve: "অনুমোদন",
  reject: "প্রত্যাখ্যান",

  // Placeholders
  namePlaceholder: "আপনার পূর্ণ নাম লিখুন",
  phonePlaceholder: "১১ ডিজিটের মোবাইল নম্বর",
  passwordPlaceholder: "পাসওয়ার্ড লিখুন",
  roomPlaceholder: "রুম নম্বর (যেমন: ৩০২)",

  // Emergency & Status
  emergencyOff: "জরুরি বন্ধ",
  emergencyNotice: "জরুরি বন্ধ নোটিশ",
  emergencyMealClosure: "জরুরি মিল বন্ধকরণ ফরম",
  closureDate: "বন্ধের তারিখ",
  closureReason: "বন্ধের সুনির্দিষ্ট কারণ",
  emergencySubmit: "জরুরি বন্ধ নিশ্চিত করুন",
  pendingApprovals: "অপেক্ষমাণ অনুমোদনসমূহ",
  activeUsersCount: "সক্রিয় মেম্বার সংখ্যা",
  auditReason: "অ্যাডমিন অ্যাকশনের কারণ",
  deadlinePassedWarning: "সকাল ১০:০০ টার পর আজকের মিল পরিবর্তন সম্ভব নয়",
  approveUser: "অনুমোদন করুন",
  rejectUser: "প্রত্যাখ্যান করুন",
  activeStatus: "অনুমোদিত",
  pendingStatus: "অপেক্ষমাণ",
  pendingApprovalNotice: "অ্যাকাউন্ট অনুমোদনের অপেক্ষায় রয়েছে",
  contactAdmin: "অনুমোদনের জন্য অ্যাডমিনের সাথে সরাসরি যোগাযোগ করুন",
  approved: "অনুমোদিত",
  pending: "অপেক্ষমাণ",
  rejected: "প্রত্যাখ্যাত",

  // Public Today's Meal
  publicTodaysMeal: "আজকের মিল (পাবলিক)",
  publicTodaysMealTitle: "আজকের মিল ও ফিঙ্গারপ্রিন্ট সামারি",
  publicTodaysMealSubtitle: "আজকের মিল ডিক্লেয়ারেশন ও মেম্বারদের ব্যালেন্সের সুরক্ষিত ওভারভিউ",
  maskedPhoneLabel: "মোবাইল নম্বর",
  maskedBalanceLabel: "ব্যালেন্স",
  clickEyeToLogin: "সম্পূর্ণ দেখতে চোখ আইকনে ক্লিক করুন",
  loginToSeeDetails: "বিস্তারিত তথ্য দেখতে অ্যাকাউন্টে লগইন করুন",
  publicNoticeBanner: "সুরক্ষার জন্য মেম্বারদের মোবাইল নম্বর ও ব্যালেন্স আংশিক আবৃত রয়েছে। সম্পূর্ণ দেখতে লগইন করুন।",
};
